manufacturers:
  kia:
    hebrew: "קיה"
    english: "Kia"
    manufacturer_id: 48
    models:
      picanto:
        hebrew: "פיקנטו"
        english: "Picanto"
        model_id: 10711
      sportage:
        hebrew: "ספורטז'"
        english: "Sportage"
        model_id: 10720
      ceed:
        hebrew: "סיד"
        english: "ceed"
        model_id: 10698  # Note: Based on Kia Ceed (סיד) which may be the same as Cerato
      sorento:
        hebrew: "סורנטו"
        english: "Sorento"
        model_id: 10718
      rio:
        hebrew: "ריו"
        english: "Rio"
        model_id: 10714
  toyota:
    hebrew: "טויוטה"
    english: "Toyota"
    manufacturer_id: 19
    models:
      corolla:
        hebrew: "קורולה"
        english: "Corolla"
        model_id: 10226
      rav4:
        hebrew: "RAV4"
        english: "RAV4"
        model_id: 10238
      yaris:
        hebrew: "יאריס"
        english: "Yaris"
        model_id: 10247
      auris:
        hebrew: "אוריס"
        english: "Auris"
        model_id: 10218
  hyundai:
    hebrew: "יונדאי"
    english: "Hyundai"
    manufacturer_id: 21
    models:
      i20:
        hebrew: "i20"
        english: "i20"
        model_id: 10273
      elantra:
        hebrew: "אלנטרה"
        english: "Elantra"
        model_id: 10263
      tucson:
        hebrew: "טוסון"
        english: "Tucson"
        model_id: 10291
      i30:
        hebrew: "i30"
        english: "i30"
        model_id: 10276
      i10:
        hebrew: "i10"
        english: "i10"
        model_id: 10272
      accent:
        hebrew: "אקסנט"
        english: "Accent"
        model_id: 10275
  mazda:
    hebrew: "מאזדה"
    english: "Mazda"
    manufacturer_id: 27
    models:
      3:
        hebrew: "3"
        english: "3"
        model_id: 10332
      cx_5:
        hebrew: "CX-5"
        english: "CX-5"
        model_id: 10342
  honda:
    hebrew: "הונדה"
    english: "Honda"
    manufacturer_id: 17
    models:
      civic:
        hebrew: "סיוויק"
        english: "Civic"
        model_id: 10182
      jazz:
        hebrew: "ג'אז"
        english: "Jazz"
        model_id: 10188
  subaru:
    hebrew: "סובארו"
    english: "Subaru"
    manufacturer_id: 35
    models:
      forester:
        hebrew: "פורסטר"
        english: "Forester"
        model_id: 10476
  skoda:
    hebrew: "סקודה"
    english: "Skoda"
    manufacturer_id: 40
    models:
      octavia:
        hebrew: "אוקטביה"
        english: "Octavia"
        model_id: 10547
      karoq:
        hebrew: "קארוק"
        english: "Karoq"
        model_id: 10545
  nissan:
    hebrew: "ניסאן"
    english: "Nissan"
    manufacturer_id: 32
    models:
      micra:
        hebrew: "מיקרה"
        english: "Micra"
        model_id: 10438
      qashqai:
        hebrew: "קשקאי"
        english: "Qashqai"
        model_id: 10449
  chevrolet:
    hebrew: "שברולט"
    english: "Chevrolet"
    manufacturer_id: 52
    models:
      spark:
        hebrew: "ספארק"
        english: "Spark"
        model_id: 10796
      equinox:
        hebrew: "אקווינוקס"
        english: "Equinox"
        model_id: 10784
  mitsubishi:
    hebrew: "מיצובישי"
    english: "Mitsubishi"
    manufacturer_id: 30
    models:
      asx:
        hebrew: "ASX"
        english: "ASX"
        model_id: 10366
  suzuki:
    hebrew: "סוזוקי"
    english: "Suzuki"
    manufacturer_id: 36
    models:
      swift:
        hebrew: "סוויפט"
        english: "Swift"
        model_id: 10497
  peugeot:
    hebrew: "פיג'ו"
    english: "Peugeot"
    manufacturer_id: 46
    models:
      208:
        hebrew: "208"
        english: "208"
        model_id: 10659
      3008:
        hebrew: "3008"
        english: "3008"
        model_id: 10661
  renault:
    hebrew: "רנו"
    english: "Renault"
    manufacturer_id: 51
    models:
      clio:
        hebrew: "קליאו"
        english: "Clio"
        model_id: 10751
  volkswagen:
    hebrew: "פולקסווגן"
    english: "Volkswagen"
    manufacturer_id: 41
    models:
      golf:
        hebrew: "גולף"
        english: "Golf"
        model_id: 10562
      polo:
        hebrew: "פולו"
        english: "Polo"
        model_id: 10571
  seat:
    hebrew: "סיאט"
    english: "Seat"
    manufacturer_id: 37
    models:
      ibiza:
        hebrew: "איביזה"
        english: "Ibiza"
        model_id: 10507
      leon:
        hebrew: "לאון"
        english: "Leon"
        model_id: 10509
  ford:
    hebrew: "פורד"
    english: "Ford"
    manufacturer_id: 43
    models:
      focus:
        hebrew: "פוקוס"
        english: "Focus"
        model_id: 10598
      kuga:
        hebrew: "קוגה"
        english: "Kuga"
        model_id: 10601
  opel:
    hebrew: "אופל"
    english: "Opel"
    manufacturer_id: 2
    models:
      corsa:
        hebrew: "קורסה"
        english: "Corsa"
        model_id: 10038
  jeep:
    hebrew: "ג'יפ"
    english: "Jeep"
    manufacturer_id: 10
    models:
      avenger:
        hebrew: "אבנג'ר"
        english: "Avenger"
        model_id: 13199
  citroen:
    hebrew: "סיטרואן"
    english: "Citroen"
    manufacturer_id: 38
    models:
      c5_aircross:
        hebrew: "איירקרוס C5"
        english: "C5 Aircross"
        model_id: 11551